### PR TITLE
Boost build script

### PR DESCRIPTION
**Pull request by mliberman**
This is a python port of the `build-c++` script found [here](https://github.com/danoli3/ofxiOSBoost/blob/master/scripts/build-libc%2B%2B). It defines the Boost linked libraries and header-only dependencies at the top of the file, and then proceeds to:
* Creates an empty `build` folder in the submodule's root.
* Downloads and unpacks the appropriate Boost tarball based on the version.
* Build the appropriate libraries.
* Package the libraries into a "fat lib" at `lib/libboost.a`.
* Use `bcp` to extract _only the headers we need_ into `include/boost`.
* Remove the `build` folder.

PTAL @petersibley 
CC @FiftyThree/team-app

### CODE REVIEW

**Comment by mliberman** [comment]
I stole a ton of python utilities from our own build script.

**Comment by petersibley** [comment]
I'd make one change which is to manage `lib/libboost.a` via `git lfs` so "run build script" commit would require a `git lfs add lib/libboost.a`

**Comment by petersibley** [comment]
LGTM to me. yeah wish we had a better way to manage our cross repo python stuff but this is already dramatically better than the shell script way of doing things. heads up @thomasmarsh @floatplane

**Comment by mliberman** [comment]
> so "run build script" commit would require a `git lfs add lib/libboost.a`

Can't we just setup `git lfs` once in the repo and have it track `*.a` files?

**Comment by petersibley** [comment]
Yup works for me.

**Pull request merged**
